version: '3.9'

networks:
  default:
    name: personal-site-mostafa-effati-net-front-next
    driver: bridge

services:
  front-next:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: frontend/nextjs-13-dev
    volumes:
      - './:/opt:z'
    networks:
      - default
    ports:
      - 3000:3000
    command: yarn dev